batbomb-cooldown: 5
batbomb-fuse-ticks: 2
batglide-cooldown: 5
batterang-cooldown: 5
batterang-damage: 5
hulksmash-cooldown: 5
hulkclap-cooldown: 5
hulksuction-cooldown: 5
hulkthrow-cooldown: 5
webshot-cooldown: 5
webshot-remove-delay: 10
iceshooter-ammo: 10
iceshooter-reload-speed: 2
iceshooter-damage: 5
freeze-time: 5
freeze-cooldown: 5
icepath-length: 5
spidersurround-time: 6
spidersurround-delay: 10
spidersurround-cooldown: 20
gun-damage: 3
choke-time: 3
choke-cooldown: 5
poisondart-ammo: 5
poisondart-length: 3
poisondart-reload-speed: 5
